Repository IBM/ibm-commonui-operator, pull requests merged in 2020-05, with the labels that each got.

#49 Adding bindinfo object to CSV
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#45 Update readme v1.2 template
  README.md
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, size/M

#50 Updated UBI images to 8.2-267
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#51 Changing name to ui bindinfo
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#52 Update operand version to 1.2.0
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#53 Change operand version
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#54 Changing image tag to sha
  Makefile
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#55 add beta channel
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
Labels: approved, lgtm, size/XS

#56 fix sha digest
  Makefile
  common/scripts/get_image_sha_digest.sh
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#58 add 1.2.1 dev channel, update operator version
  .osdk-scorecard.yaml
  common/scripts/get_image_sha_digest.sh
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
  pkg/resources/container.go
  version/version.go
Labels: approved, lgtm, size/XL

#57 Add TLS support to common-web-ui backend
  cmd/manager/main.go
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#59 Updated csv description
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#60 Use imageReg from CR if set
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
Labels: approved, size/S

#61 extra comma in csv
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
Labels: approved, size/XS

#62 adding updated dependencies
  go.mod
Labels: approved, size/XS

#63 make res/req limits dynamic
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/operators.ibm.com_commonwebuis_crd.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/M

#64 update openapi file
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/S

#66 pod restart for req limits from cr
  pkg/resources/reconcile.go
Labels: approved, lgtm, size/S

#65 Update4 content cert
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_legacyheaders_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/operators.ibm.com_legacyheaders_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/L

#68 Upgrade wont work when changing types
  Makefile
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/operators.ibm.com_commonwebuis_crd.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/M

#69 Changing ints to strings csv
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
Labels: approved, size/XS

#67 Added detectHeaderItems to NavConfig CRD schema
  old_crds/foundation.ibm.com_navconfiguration_cp4i_cr.yaml
  old_crds/foundation.ibm.com_navconfigurations_crd.yaml
  pkg/resources/utils.go
  prev-crds/foundation.ibm.com_navconfiguration_cp4i_cr.yaml
  prev-crds/foundation.ibm.com_navconfigurations_crd.yaml
Labels: approved, lgtm, size/M

#70 Promote dev to beta 1.2.1
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
Labels: approved, size/S
