Repository IBM/ibm-commonui-operator, pull requests merged in 2020-11, with the labels that each got.

#139 Update cluster permissions
  deploy/crds/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/crds/foundation.ibm.com_v1_navconfigurationcp4i_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/apis/addtoscheme_foundation_v1.go
  pkg/apis/foundation/group.go
  pkg/apis/foundation/v1/doc.go
  pkg/apis/foundation/v1/navconfiguration_types.go
  pkg/apis/foundation/v1/register.go
  pkg/apis/foundation/v1/zz_generated.deepcopy.go
  pkg/apis/foundation/v1/zz_generated.openapi.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XXL

#142 Left-hand nav icons
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#141 Adding resource specific cluster roles
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M

#143 sha update
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#140 add namespaces env var
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#144 add cluster permissions to get services
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#145 add permissions for extenstions api group
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#146 updating service name
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/crds/foundation.ibm.com_v1_navconfigurationcp4i_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#151 Bump operator version for 3.6 Beta 2
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/operators.ibm.com_switcheritems_crd.yaml
  pkg/resources/utils.go
  version/version.go
Labels: approved, lgtm, size/XXL

#147 Left nav icons update
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#150 Update UBI version to 8.3-201
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#149 Remove version and update about modal title in navconfig
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#152 update operand shas
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#153 Moving fixes from 140 to 141
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#154 Add labels to navconfig crs
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/crds/foundation.ibm.com_v1_navconfigurationcp4i_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#155 Add use nav
  deploy/crds/foundation.ibm.com_v1_navconfigurationcp4i_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#156 Added permissions for prometheus api
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#148 fixing lint error
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#159 Added ClusterAdmin auth to Home page in NavConfig
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#158 update copyright year in about modal
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#157 Update labels for ocp 4.6
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.1/ibm-commonui-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.2/ibm-commonui-operator.v1.2.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.3/ibm-commonui-operator.v1.2.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.4/ibm-commonui-operator.v1.2.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/ibm-commonui-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/ibm-commonui-operator.v1.3.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/ibm-commonui-operator.v1.3.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
Labels: approved, lgtm, size/S

#160 Update 141 shas
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
