Repository IBM/ibm-commonui-operator, pull requests merged in 2020-10, with the labels that each got.

#135 [DO NOT MERGE] update redirect login for Edge
  README.md
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/S

#132 update operator version for cs 3.6
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/ibm-commonui-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.0/operators.ibm.com_switcheritems_crd.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#133 update management-ingress port to 8443.
  pkg/resources/container.go
Labels: approved, lgtm, size/XS

#137 Revert "update management-ingress port to 8443."
  pkg/resources/container.go
Labels: approved, lgtm, size/XS
