Repository IBM/ibm-commonui-operator, pull requests merged in 2020-03, with the labels that each got.

#20 update ingress rules
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#19 Add metering annotations to DS
  deploy/crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#21 add service account, cluster role permissions
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/M

#23 Fixing Logo and 404 errors
  deploy/crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#24 Adding catalog ui detection in nav items
  deploy/crds/foundation.ibm.com_navconfiguration_cp4i_cr.yaml
  deploy/crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#22 add environment variables for provider options
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/operators.ibm.com_commonwebuis_crd.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/M

#25 update monitoring service name
  deploy/crds/foundation.ibm.com_navconfiguration_cp4i_cr.yaml
  deploy/crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#26 Reque
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#27 Added frame-ancestors directive to CSP
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#28 fix ds name
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
Labels: approved, lgtm, size/XS

#29 update power and s390 ubi image
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#30 add metering annotations to operator
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#31 point image registry to quay
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  pkg/resources/container.go
Labels: approved, lgtm, size/S

#32 update image registry
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  pkg/resources/container.go
Labels: approved, lgtm, size/S

#33 updating channel to stable-v1
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#34 update legacy release name
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
Labels: approved, lgtm, size/XS
