Repository IBM/ibm-commonui-operator, pull requests merged in 2020-06, with the labels that each got.

#71 update memory and channel
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.2/ibm-commonui-operator.v1.2.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.2/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.2/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  version/version.go
Labels: approved, lgtm, size/XL

#72 Change operator version to latest
  deploy/olm-catalog/ibm-commonui-operator/1.2.2/ibm-commonui-operator.v1.2.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#73 update volume mount to fix upgrade
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/M

#75 Promote 122 to stable-v1
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
Labels: approved, size/XS

#76 Adding version to CR spec
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_legacyheaders_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.3/ibm-commonui-operator.v1.2.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.3/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.3/operators.ibm.com_legacyheaders_crd.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/legacyheaderservice_types.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#78 ALM Config number needs to be a string
  deploy/olm-catalog/ibm-commonui-operator/1.2.3/ibm-commonui-operator.v1.2.3.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#77 Update commonui operand version
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.3/ibm-commonui-operator.v1.2.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#81 Promoting v1.2.3 to stable-v1
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
Labels: approved, lgtm, size/XS
