Repository IBM/ibm-commonui-operator, pull requests merged in 2020-02, with the labels that each got.

#4 add resources, reconcile ds
  common/Makefile.common.mk
  deploy/crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_legacyheaders_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XXL

#9 watch reconcile legacy header resources
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#12 CSV and operator.yaml updates
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#14 Update Service account name
  deploy/role.yaml
  deploy/service_account.yaml
Labels: approved, size/S

#15 Update CSV with service account
  common/scripts/delete-csv.sh
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#16 fix daemonset security context, update legacy header image tag
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#17 update role, csv
  deploy/crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/S
