Repository IBM/ibm-commonui-operator, pull requests merged in 2020-09, with the labels that each got.

#99 update 1.3.1 operator version
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/operators.ibm.com_switcheritems_crd.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#100 Adding dashboard collector container
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
  go.mod
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/L

#101 use 1.3.1, 1.0.0, operand and dashboard sha
  Makefile
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#103 Update operand sha 1.3.1
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#104 update login title
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#105 Adding shas for sep10
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#106 Removing product version
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#102 update nav items
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#107 Update shas sept11
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#108 update 1.3.1 operand sha sept 11 9 pm
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#111 sha 9/13/2020
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#113 Adding GPL licenses
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#114 monday 09/14 7:30 sha
  deploy/olm-catalog/ibm-commonui-operator/1.3.1/ibm-commonui-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#115 Update version to 1.3.2
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/ibm-commonui-operator.v1.3.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/operators.ibm.com_switcheritems_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
  version/version.go
Labels: approved, lgtm, size/XL

#116 update operand sha, use 1.0.1 dashboard version
  Makefile
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/ibm-commonui-operator.v1.3.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#117 Adding cert canges for 1.3.2
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_legacyheaders_crd.yaml
  deploy/crds/operators.ibm.com_switcheritems_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/ibm-commonui-operator.v1.3.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/operators.ibm.com_switcheritems_crd.yaml
  pkg/apis/operators/v1alpha1/common.go
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/legacyheaderservice_types.go
  pkg/apis/operators/v1alpha1/switcheritem_types.go
  pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
Labels: approved, lgtm, size/L

#119 Updating operator sha for case bundle
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/ibm-commonui-operator.v1.3.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#118 Update data collector with new version and resource limits
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_switcheritems_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/ibm-commonui-operator.v1.3.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/operators.ibm.com_commonwebuis_crd.yaml
  deploy/operator.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/switcheritem_types.go
  pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/L

#120 Added comma to alm-examples
  deploy/olm-catalog/ibm-commonui-operator/1.3.2/ibm-commonui-operator.v1.3.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#122 Adding 1.3.3 csv to operator1
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/ibm-commonui-operator.v1.3.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/operators.ibm.com_switcheritems_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#121 update UBI to 8.2-349
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#123 9/21 operand sha
  Makefile
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/ibm-commonui-operator.v1.3.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#124 Adding disabled items
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#125 Adding doc link
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#126 hardcode ingress frame domain
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#128 Friday sha updates
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/ibm-commonui-operator.v1.3.3.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#129 Update container.go for issue 40567
  pkg/resources/container.go
Labels: approved, lgtm, size/S

#130 wednesday 09/30 sha
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/ibm-commonui-operator.v1.3.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#131 correct sha update
  deploy/olm-catalog/ibm-commonui-operator/1.3.3/ibm-commonui-operator.v1.3.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
