Repository IBM/ibm-commonui-operator, pull requests merged in 2020-12, with the labels that each got.

#162 Update 141 shas
  deploy/operator.yaml
Labels: lgtm, ok-to-test, size/XS

#163 Update 141 shas
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/ibm-commonui-operator.v1.4.1.clusterserviceversion.yaml
Labels: lgtm, ok-to-test, size/XS

#164 update release version
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/operators.ibm.com_switcheritems_crd.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#165 Addons extension
  cmd/manager/main.go
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L
