Repository IBM/ibm-commonui-operator, pull requests merged in 2020-08, with the labels that each got.

#93 Integrate with new cicd
  Makefile
Labels: approved, lgtm, size/M

#80 Cloud pak switcher
  deploy/crds/operators.ibm.com_switcheritems_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_switcheritem_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/ibm-commonui-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/operators.ibm.com_switcheritems_crd.yaml
  deploy/role.yaml
  go.mod
  pkg/apis/operators/v1alpha1/switcheritem_types.go
  pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#94 Adding prow auth
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/XS

#95 update 1.3.0 operand and operator sha
  Makefile
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/ibm-commonui-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#96 change cr cpu resource names
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/ibm-commonui-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/operators.ibm.com_commonwebuis_crd.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#97 adding quotes to resources in csv
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/ibm-commonui-operator.v1.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#98 remove replicas required field
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/operators.ibm.com_commonwebuis_crd.yaml
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS
