Repository IBM/ibm-commonui-operator, pull requests merged in 2020-07, with the labels that each got.

#84 Adding 1.2.4 version
  deploy/olm-catalog/ibm-commonui-operator/1.2.4/ibm-commonui-operator.v1.2.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.4/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.4/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  pkg/resources/utils.go
  version/version.go
Labels: approved, lgtm, size/XL

#85 Login title was incorrect
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#83 [WIP] Add Deployment for ui
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/ibm-commonui-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/operators.ibm.com_commonwebuis_crd.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, do-not-merge/work-in-progress, lgtm, size/L

#86 change common ui cr structure
  deploy/.DS_Store
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/.DS_Store
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/ibm-commonui-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/operators.ibm.com_commonwebuis_crd.yaml
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/L

#87 fix comma in alm examples
  deploy/olm-catalog/ibm-commonui-operator/1.3.0/ibm-commonui-operator.v1.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#88 Update UBI image to 8.2.339
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#89 Update UBI image for release v1.2.4
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#90 update operator sha 3.4.1 fix 3
  deploy/olm-catalog/ibm-commonui-operator/1.2.4/ibm-commonui-operator.v1.2.4.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#91 add 1.2.4 beta csv to master
  deploy/olm-catalog/ibm-commonui-operator/1.2.4/ibm-commonui-operator.v1.2.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.4/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.4/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XL

#92 add 1.2.4 stable-v1
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
Labels: approved, lgtm, size/XS
