Repository IBM/ibm-commonui-operator, pull requests merged in 2020-04, with the labels that each got.

#37 update CSV with keywords and categories
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#38 update operand/operator images version
  .osdk-scorecard.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#39 Adding operand request for dependencies
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#40 updating replaces version
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#41 Removing replaces in 1.1.0 csv
  deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#42 make sa dynamic
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml
  deploy/operator.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#43 Removing legacyheaders and adding lint fixes
  Makefile
  README.md
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.sum
  old_crds/foundation.ibm.com_navconfiguration_cp4i_cr.yaml
  old_crds/foundation.ibm.com_navconfigurations_crd.yaml
  old_crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#44 Adding scc restricted
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#46 Update req limits
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#48 Update broken csv
  deploy/olm-catalog/ibm-commonui-operator/1.2.0/ibm-commonui-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, size/XS

#47 Update UBI image to 8.1-409
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS
