Repository IBM/ibm-commonui-operator, pull requests merged in 2021-08, with the labels that each got.

#231 Updater operator dependencies to use v1 Ingress
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XXL

#232 Update operator version to 1.9
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.9.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.9.0/ibm-commonui-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.9.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.9.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.9.0/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#234 Update go version to 1.16.6 in eus stream
  go.mod
Labels: approved, lgtm, size/XS

#233 Update go version to 1.16.6 in cd stream
  go.mod
Labels: approved, lgtm, size/XS

#236 remove unused base images file
  base-images.json
Labels: approved, lgtm, size/XS

#237 opt in for automatic ubi image updates
  base_images.json
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/M

#238 Support optional install zen
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: size/L, approved, lgtm

#239 adding images to relatedImages
  deploy/olm-catalog/ibm-commonui-operator/1.9.0/ibm-commonui-operator.v1.9.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
