Repository IBM/ibm-commonui-operator, pull requests merged in 2021-02, with the labels that each got.

#182 Added check to preserve cert-manager added labels
  pkg/resources/container.go
  pkg/resources/reconcile.go
Labels: approved, lgtm, size/S

#183 Added check to preserve cert-manager added labels in EUS branch
  pkg/resources/container.go
  pkg/resources/reconcile.go
Labels: approved, lgtm, size/S

#181 Remove Data collector
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/operator.yaml
  pkg/apis/foundation/v1/zz_generated.deepcopy.go
  pkg/apis/operators/v1alpha1/commonwebuiservice_types.go
  pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#185 Updated NavConfig IAM links and added requeue logic for routes
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/crds/foundation.ibm.com_v1_navconfigurationcp4i_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#186 update manifest version
  Makefile
Labels: approved, size/XS

#187 Remove type for nav crd
  deploy/crds/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/foundation.ibm.com_navconfigurations_crd.yaml
Labels: approved, lgtm, size/XS

#188 Upgrade fix and manifest version update
  Makefile
  deploy/crds/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.1/foundation.ibm.com_navconfigurations_crd.yaml
Labels: approved, lgtm, size/XS

#189 update navItems on upgrade from prev versions
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/S

#190 bump operator version
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.1/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.1/ibm-commonui-operator.v1.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.1/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.1/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.1/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#191 Include replaces statement on CSV
  deploy/olm-catalog/ibm-commonui-operator/1.5.1/ibm-commonui-operator.v1.5.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
