Repository IBM/ibm-commonui-operator, pull requests merged in 2021-04, with the labels that each got.

#203 update default limits
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/M

#205 Update owners
  OWNERS
Labels: approved, lgtm, size/XS

#204 Update permissions for mcm
  deploy/olm-catalog/ibm-commonui-operator/1.4.2/ibm-commonui-operator.v1.4.2.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M

#206 update data collector image version
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.2/ibm-commonui-operator.v1.4.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#207 Network perm for promethues
  deploy/olm-catalog/ibm-commonui-operator/1.4.2/ibm-commonui-operator.v1.4.2.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#202 Update version for 2q release
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/ibm-commonui-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  version/version.go
Labels: approved, lgtm, size/XXL

#211 Query fix and update version for fixpack
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.3/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.3/ibm-commonui-operator.v1.5.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.3/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.3/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.3/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#212 update ubi to latest for twistlock and cves
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#213 Reduce api verbs and pod restarts
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/ibm-commonui-operator.v1.6.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#209 licensing-permisssions-update
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/crds/foundation.ibm.com_v1_navconfigurationcp4i_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/ibm-commonui-operator.v1.6.0.clusterserviceversion.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#214 update copyrights and add check script
  hack/boilerplate.go.txt
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
  scripts/copyright-check.sh
  version/version.go
Labels: approved, lgtm, size/L
