Repository IBM/ibm-commonui-operator, pull requests merged in 2021-01, with the labels that each got.

#166 Changes for auto sha updates
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#167 add auto sha updates for dashboard collector
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/S

#168 updating base image values to ubi min image rebuilds
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#171 Admin hub console link
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#169 Redis client certs config map
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#173 Update cluster permissions
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#174 Added role for getting must-gather jobs
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#177 Added TopologySpreadConstraints for EUS release
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/S

#176 Updated csv for v3 channel
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#175 Added TopologySpreadConstraints to deployment pods
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/S

#178 Remove redis cr
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/M

#179 Make nav items namespace dynamic
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/crds/foundation.ibm.com_v1_navconfigurationcp4i_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.0/ibm-commonui-operator.v1.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#180 allow cloudpak admin to access home nav
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
Labels: approved, lgtm, size/XS
