Repository IBM/ibm-commonui-operator, pull requests merged in 2021-03, with the labels that each got.

#192 Upgrade to the latest version of Go in EUS
  go.mod
Labels: approved, lgtm, size/XS

#193 PSIRT upgrade gogo/protobuf
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#194 upgrade gogo v1.3.2
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#195 update title texts
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.1/ibm-commonui-operator.v1.5.1.clusterserviceversion.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#196 update eus operator version
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.2/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.2/ibm-commonui-operator.v1.4.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.2/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.2/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.2/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
  version/version.go
Labels: approved, lgtm, size/XXL

#199 update version for fixpack 1Q
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.2/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.2/ibm-commonui-operator.v1.5.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.2/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.2/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.5.2/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#200 Update memory limits for cpu and requests
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/S

#201 Update ubi base images for EUS
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS
