Repository IBM/ibm-commonui-operator, pull requests merged in 2021-09, with the labels that each got.

#241 rebuild for new prow container
  Makefile
Labels: approved, lgtm, size/XS

#242 Related images addition
  deploy/olm-catalog/ibm-commonui-operator/1.9.0/ibm-commonui-operator.v1.9.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#244 update operator version to 1.10.0
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.10.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.10.0/ibm-commonui-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.10.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.10.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.10.0/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#243 Support zen nls package upload
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#246 Updates for new login page
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.10.0/ibm-commonui-operator.v1.10.0.clusterserviceversion.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#245 Initial commit, add code to detect, update, delete resources
  pkg/controller/add_commonwebuizen.go
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#247 Return error when deployment not found
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
Labels: approved, lgtm, size/XS

#248 update zen controller to reconcile updates to product-configmap
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/resources/utils.go
Labels: size/L, approved, lgtm

#249 Delete bind info
  deploy/olm-catalog/ibm-commonui-operator/1.10.0/ibm-commonui-operator.v1.10.0.clusterserviceversion.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/resources/container.go
  pkg/resources/utils.go
Labels: size/L, approved, lgtm

#250 Initial version bump project-k
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/4.0.0-k/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/4.0.0-k/ibm-commonui-operator.v4.0.0-k.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/4.0.0-k/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/4.0.0-k/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/4.0.0-k/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#251 trigger build
  deploy/olm-catalog/ibm-commonui-operator/4.0.0-k/ibm-commonui-operator.v4.0.0-k.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#252 updates for nls fixes and adjust title in zen product configmap
  pkg/resources/utils.go
Labels: approved, lgtm, size/S
