Repository IBM/ibm-commonui-operator, pull requests merged in 2021-05, with the labels that each got.

#216 updating amd to latest and SHAs for ppc61le and s390x
  Makefile
Labels: approved, lgtm, size/XS

#217 update deprecated crd version
  deploy/crds/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_legacyheaders_crd.yaml
  deploy/crds/operators.ibm.com_switcheritems_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_switcheritems_crd.yaml
Labels: approved, lgtm, size/XXL

#218 Add missing field for updated CRD
  deploy/crds/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/crds/operators.ibm.com_commonwebuis_crd.yaml
  deploy/crds/operators.ibm.com_legacyheaders_crd.yaml
  deploy/crds/operators.ibm.com_switcheritems_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.6.0/operators.ibm.com_switcheritems_crd.yaml
Labels: approved, lgtm, size/M
