Repository IBM/ibm-commonui-operator, pull requests merged in 2021-11, with the labels that each got.

#262 [release-k] Kubernetes cluster Type
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/M

#268 update project k config map name
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/XS

#270 bump version to 1.12.0
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.12.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.12.0/ibm-commonui-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.12.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.12.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.12.0/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#269 fix nav
  deploy/olm-catalog/ibm-commonui-operator/1.4.3/ibm-commonui-operator.v1.4.3.clusterserviceversion.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: size/L, approved

#267 add cncf changes
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/resources/container.go
Labels: size/L, approved, lgtm

#271 fix lint rules for cd assessment
  deploy/olm-catalog/ibm-commonui-operator/1.4.3/ibm-commonui-operator.v1.4.3.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
Labels: approved, lgtm, size/XS

#272 Removed CSP header from ingresses
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#274 [release-k] zen card extensions for cncf cluster and updates on upgrade
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/resources/utils.go
Labels: size/L, approved, lgtm

#275 [Pentest-EUS] remove secret env var from container
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/M

#276 [CD] Zen updates cncf
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/resources/utils.go
Labels: size/L, approved, lgtm

#277 add env vars check
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
Labels: approved, lgtm, size/S

#278 [Pentest-CD] remove secret env var from container
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/controller/commonwebuizen/commonwebuizen_controller.go
  pkg/controller/legacyheaderservice/legacyheaderservice_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/M

#279 update about panel for ocrad-bower
  deploy/crds/foundation.ibm.com_v1_navconfiguration_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.12.0/ibm-commonui-operator.v1.12.0.clusterserviceversion.yaml
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/S
