Repository IBM/ibm-commonui-operator, pull requests merged in 2021-06, with the labels that each got.

#219 add support to use common tagged ubi image for operator containers
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, size/M

#220 small change to trigger rebuild for new ubi
  Makefile
Labels: approved, size/XS

#221 Bump eus version to 1.4.3 for next FP
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.3/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.3/ibm-commonui-operator.v1.4.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.3/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.3/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.4.3/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#222 Bump operator versions for drop 3
  Makefile
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.7.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.7.0/ibm-commonui-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.7.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.7.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.7.0/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#224 add internal tls cert volume
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/container.go
Labels: approved, lgtm, size/S
