Repository IBM/ibm-commonui-operator, pull requests merged in 2022-01, with the labels that each got.

#282 remove codecov
  Makefile
  common/scripts/codecov.sh
Labels: size/L, approved, lgtm

#283 remove code cov
  Makefile
  common/scripts/codecov.sh
Labels: size/L, approved, lgtm

#284 patch vulnerable crypto
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#285 explicitly require crypto package to make twistlock happy
  go.mod
Labels: approved, size/XS

#286 Add permission for licensing new auth method
  deploy/olm-catalog/ibm-commonui-operator/1.13.0/ibm-commonui-operator.v1.13.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S
