Repository IBM/ibm-commonui-operator, pull requests merged in 2022-04, with the labels that each got.

#294 Sgrube version bump 1.16.0
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.16.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.16.0/ibm-commonui-operator.v1.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.16.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.16.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.16.0/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#297 update field name for card ids created for zen
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#300 fix build on power and z
  Makefile
Labels: approved, lgtm, size/XS

#302 update to use icr/cpopen registry
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  common/config/.hadolint.yml
  config/manager/manager.yaml
  config/samples/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  controllers/resources/constants.go
Labels: approved, lgtm, size/S

#303 missed icr reference
  controllers/resources/constants.go
Labels: approved, lgtm, size/XS

#305 README update
  README.md
Labels: approved, lgtm, size/S

#304 handle conditions where new env vars did not exist on upgrade
  controllers/commonwebuizen/commonwebuizen_controller.go
Labels: approved, lgtm, size/M

#306 clean up zen logs
  controllers/commonwebuizen/commonwebuizen_controller.go
Labels: approved, lgtm, size/XS
