Repository IBM/ibm-commonui-operator, pull requests merged in 2022-03, with the labels that each got.

#290 update version to 1.15.0
  deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.15.0/foundation.ibm.com_navconfigurations_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.15.0/ibm-commonui-operator.v1.15.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.15.0/operators.ibm.com_commonwebuis_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.15.0/operators.ibm.com_legacyheaders_crd.yaml
  deploy/olm-catalog/ibm-commonui-operator/1.15.0/operators.ibm.com_switcheritems_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#291 Update api ingress for cncf logout
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#292 set reconciled version in status
  pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
Labels: approved, lgtm, size/XS
