Repository IBM/ibm-commonui-operator, pull requests merged in 2022-08, with the labels that each got.

#319 version bump for cs3.20.1 to 1.18.1
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  version/version.go
Labels: approved, lgtm, size/M

#320 bump version for CS3.21 to 1.19.0
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  version/version.go
Labels: approved, lgtm, size/M

#322 requeue console link creation
  controllers/commonwebui/commonwebui_controller.go
  controllers/resources/customresources.go
Labels: approved, lgtm, size/S

#323 update about modal cd
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/foundation.ibm.com_v1_navconfiguration_cr.yaml
  controllers/resources/constants.go
Labels: approved, lgtm, size/XS
