Repository IBM/ibm-commonui-operator, pull requests merged in 2022-11, with the labels that each got.

#334 Add license
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/foundation.ibm.com_v1_navconfiguration_cr.yaml
  controllers/resources/constants.go
Labels: approved, lgtm, size/XS

#339 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#340 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#341 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#338 remove cluster level permissions and disable zen
  Makefile
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/commonwebui/commonwebui_controller.go
  controllers/commonwebuizen/commonwebuizen_controller.go
Labels: size/L, approved, lgtm

#342 add route permissions
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/S

#343 version bump 1.21.0/3.23.0
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  version/version.go
Labels: approved, lgtm, size/M
