Repository IBM/ibm-commonui-operator, pull requests merged in 2023-06, with the labels that each got.

#429 preserve tls certs in route
  controllers/resources/routes.go
Labels: approved, size/XS

#432 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#433 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, lgtm, size/S
