Repository IBM/ibm-commonui-operator, pull requests merged in 2023-01, with the labels that each got.

#348 Update container.go to add OSAUTH_ENABLED for enabling OS
  controllers/resources/container.go
Labels: approved, lgtm, size/S

#349 fix env settings
  controllers/resources/container.go
Labels: approved, lgtm, size/S

#352 force rebuild
  Makefile
Labels: approved, lgtm, size/XS

#353 force build
  Makefile
Labels: approved, lgtm, size/XS

#355 create config configmap
  controllers/commonwebui/commonwebui_controller.go
  controllers/commonwebuizen/commonwebuizen_controller.go
  controllers/resources/configmaps.go
Labels: approved, lgtm, size/M

#354 add config configmap
  controllers/commonwebui/commonwebui_controller.go
  controllers/commonwebuizen/commonwebuizen_controller.go
  controllers/resources/configmaps.go
Labels: approved, lgtm, size/M

#356 do not update zen product configmap
  controllers/commonwebuizen/commonwebuizen_controller.go
  controllers/resources/configmaps.go
Labels: size/L, approved, lgtm

#357 remove non dependent services
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#358 remove walkme
  controllers/resources/configmaps.go
  controllers/resources/constants.go
Labels: approved, lgtm, size/M

#359 add multinamspace watching support
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-commonui-operator.clusterserviceversion.yaml
  controllers/commonwebui/commonwebui_controller.go
  controllers/commonwebuizen/commonwebuizen_controller.go
  main.go
Labels: approved, lgtm, size/M

#361 update artifactory locations
  Dockerfile
  Dockerfile.orig
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/M

#363 new artifactory locations
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/S

#360 reduce dropdown options and adjust title
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/foundation.ibm.com_v1_navconfiguration_cr.yaml
  controllers/commonwebui/commonwebui_controller.go
  controllers/resources/constants.go
  controllers/resources/navconfigs.go
Labels: size/L, approved, lgtm

#364 version bump 1.21.1/3.23.1
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  version/version.go
Labels: approved, lgtm, size/M

#362 update artifactory locations
  Dockerfile
  Dockerfile.orig
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/M

#365 fix twistlock vuln jwt
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#366 watchlist from namespace scope
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#367 remove replaces
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#368 watch certificate secrets
  controllers/commonwebui/commonwebui_controller.go
  controllers/resources/routes.go
Labels: approved, lgtm, size/XS

#369 use filtered cache
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/M

#370 remove zen controller
  controllers/commonwebui/commonwebui_controller.go
  controllers/commonwebuizen/commonwebuizen_controller.go
  controllers/resources/configmaps.go
  controllers/resources/constants.go
  controllers/resources/customresources.go
  controllers/resources/utils.go
  go.mod
  main.go
Labels: approved, size/XXL, lgtm
