Repository IBM/ibm-commonui-operator, pull requests merged in 2024-04, with the labels that each got.

#469 whitesource updates
  go.mod
  go.sum
Labels: approved, size/XS

#473 Sgrube sc2 63203 ws2
  go.mod
  go.sum
Labels: approved, size/S

#474 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, lgtm, size/S

#471 preserve customer route labels
  controllers/resources/routes.go
Labels: approved, size/XS

#472 preserve customer route labels
  controllers/resources/routes.go
Labels: approved, size/XS

#468 updates for whitesource vunls
  go.mod
  go.sum
Labels: approved, size/XS

#475 update apimachinery for ws
  go.mod
  go.sum
Labels: approved, size/S

#476 twistlock fix for net http
  go.mod
  go.sum
Labels: approved, size/S

#477 twistlock fix for net http
  go.mod
  go.sum
Labels: approved, size/S

#478 aqua updates
  go.mod
  go.sum
Labels: approved, size/M

#480 remove old image sha targets for source scan
  Makefile
  common/scripts/get_image_sha_digest.sh
Labels: approved, size/M

#481 remove old image sha targets for source scan
  Makefile
  common/scripts/get_image_sha_digest.sh
Labels: approved, size/M
