Repository IBM/ibm-commonui-operator, pull requests merged in 2024-08, with the labels that each got.

#500 cicd version bump automation for pipelines/CS-sc2.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#501 remove routes when zenFrontDoor enabled
  apis/operator/v1alpha1/authentication_types.go
  apis/operator/v1alpha1/groupversion_info.go
  apis/operator/v1alpha1/operandrequest_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  controllers/commonwebui/commonwebui_controller.go
  controllers/resources/routes.go
  main.go
Labels: approved, size/XXL

#502 updates for security context
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/resources/container.go
  controllers/resources/deepequals.go
Labels: approved, size/S

#504 update base image in dockerfile
  Dockerfile
Labels: approved, size/XS

#505 update base image in dockerfile
  Dockerfile
Labels: approved, size/XS

#506 rollback image update
  Dockerfile
Labels: approved, size/XS

#507 rollback image update
  Dockerfile
Labels: approved, size/XS
