Repository IBM/ibm-commonui-operator, pull requests merged in 2024-12, with the labels that each got.

#520 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#519 manifest updates for non OLM
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/samples/operators.ibm.com_v1alpha1_commonwebui_cr.yaml
  main.go
Labels: size/L, approved

#522 updates for twistlock
  go.mod
  go.sum
Labels: approved, size/XS

#524 whitesource updates
  go.mod
  go.sum
Labels: approved, size/S
