Repository IBM/ibm-commonui-operator, pull requests merged in 2024-01, with the labels that each got.

#461 update memory limit of operator pod
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, size/XS

#462 update pod anti affinity keyword to zone
  controllers/resources/deployments.go
Labels: approved, size/XS

#463 update affinity rules for zone
  controllers/resources/deployments.go
Labels: approved, size/S

#464 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S
