Repository IBM/ibm-commonui-operator, pull requests merged in 2024-07, with the labels that each got.

#489 cicd version bump automation for pipelines/CS-sc2.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, lgtm, size/S

#490 use cert apis from ibm cert mgr operator
  controllers/commonwebui/commonwebui_controller.go
  controllers/resources/certificates.go
  controllers/resources/deepequals.go
  go.mod
  go.sum
  main.go
Labels: size/L, approved

#492 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, lgtm, size/S

#493 update to UBI9
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, size/XS

#494 update to UBI9
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, size/XS

#491 use cert apis from ibm cert mgr operator
  controllers/commonwebui/commonwebui_controller.go
  controllers/resources/certificates.go
  controllers/resources/deepequals.go
  go.mod
  go.sum
  main.go
Labels: size/L, approved

#495 update qemu for power and ubi9
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, size/XS

#496 qemu power update
  Makefile
Labels: approved

#497 build architectures natively - remove qemu (for ubi9)
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/scripts/multiarch_image.sh
Labels: size/L, approved

#498 fix multiarch build
  Makefile
Labels: approved, size/XS

#499 move to multiarch build
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/scripts/multiarch_image.sh
Labels: size/L, approved
