Repository IBM/ibm-commonui-operator, pull requests merged in 2024-09, with the labels that each got.

#508 update copyrights for about panel
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/foundation.ibm.com_v1_navconfiguration_cr.yaml
  controllers/resources/constants.go
Labels: approved, size/XS

#509 fix ua-parser-js license reference
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/foundation.ibm.com_v1_navconfiguration_cr.yaml
  controllers/resources/constants.go
Labels: approved, size/XS

#510 cicd version bump automation for pipelines/CS-sc2.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, lgtm, size/S

#511 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#512 remove uaparser from notices, is MIT now
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/samples/foundation.ibm.com_v1_navconfiguration_cr.yaml
  controllers/resources/constants.go
Labels: approved, size/XS
