Repository IBM/ibm-commonui-operator, pull requests merged in 2025-02, with the labels that each got.

#536 fix values.yaml entitlement key var
  helm/values.yaml
Labels: approved

#537 adjust values to yaml for potential sub charting
  helm/templates/02-role-binding.yaml
  helm/templates/03-operator-deployment.yaml
  helm/values.yaml
Labels: approved, size/S

#539 rollback rh cert csv changes
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved, size/S

#540 rollback rh cert changes for helm deployment
  helm/templates/03-operator-deployment.yaml
Labels: approved

#541 chart adjustments
  helm/templates/00-service-account.yaml
  helm/templates/01-role.yaml
  helm/templates/02-role-binding.yaml
  helm/templates/03-operator-deployment.yaml
Labels: approved, size/XS

#542 chart adjustment
  helm/templates/01-role.yaml
  helm/templates/03-operator-deployment.yaml
Labels: approved

#543 Sgrube cd 65706 rhcrb5
  bundle/metadata/annotations.yaml
  ci.yaml
  config.yaml
Labels: approved

#544 update for redhat cert linting
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  helm/templates/03-operator-deployment.yaml
Labels: approved, size/S

#545 redhat cert updates
  bundle/manifests/foundation.ibm.com_navconfigurations.yaml
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#546 redhat cert updates
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved

#547 redhat cert updates
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved

#548 redhat cert updates
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved

#549 redhat cert updates
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
Labels: approved

#550 redhat cert updates
  bundle/metadata/annotations.yaml
Labels: approved, size/XS

#552 add RELATED_IMAGE to common web ui image env var
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-commonui-operator.clusterserviceversion.yaml
  controllers/resources/deployments.go
  helm/templates/03-operator-deployment.yaml
Labels: approved, size/S

#553 cicd version bump automation for pipelines/CS-sc2.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#554 fix license annotations for odlm
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  helm/templates/03-operator-deployment.yaml
Labels: approved, size/S

#555 updates for non olm chart
  helm-cluster-scoped/Chart.yaml
  helm/templates/00-rbac.yaml
  helm/templates/00-service-account.yaml
  helm/templates/01-role.yaml
  helm/templates/02-role-binding.yaml
  helm/templates/03-operator-deployment.yaml
  helm/values.yaml
Labels: approved, size/XL

#556 update channel for certification
  bundle/metadata/annotations.yaml
Labels: approved

#558 Sgrube cd 65695 nonolmchart2
  helm/templates/00-rbac.yaml
Labels: size/L, approved

#559 rebuild
  README.md
Labels: approved

#560 reduce rbac.yaml file for non-olm
  helm/templates/00-rbac.yaml
Labels: size/L, approved

#561 rebuild
  Makefile
Labels: approved

#563 fix cluster scope chart name
  helm-cluster-scoped/Chart.yaml
Labels: approved, size/XS
