Repository IBM/ibm-commonui-operator, pull requests merged in 2025-03, with the labels that each got.

#564 update tethered namespaces var
  helm/templates/00-rbac.yaml
Labels: approved, size/XS

#568 upgrade of go and controller-gen for sec updates
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  controllers/resources/ingresses.go
  go.mod
  go.sum
Labels: approved, size/M

#569 upgrade of go and controller-gen for sec updates
  Makefile
  go.mod
  go.sum
Labels: approved, size/M

#571 remove dependency on nss for non-olm
  helm/templates/03-operator-deployment.yaml
  helm/values.yaml
Labels: approved, size/S

#573 add support for labels to non-olm charts
  helm/templates/00-rbac.yaml
  helm/templates/03-operator-deployment.yaml
  helm/values.yaml
Labels: approved, size/S

#574 Sgrube cd cpfs ipp
  helm/templates/03-operator-deployment.yaml
Labels: approved, size/XS

#575 Remove intent: projected label from no olm deployment
  helm/templates/03-operator-deployment.yaml
Labels: approved, size/XS

#577 updates for whitesource
  go.mod
  go.sum
Labels: approved, size/M

#576 update x/net for whitesource
  go.mod
  go.sum
Labels: approved, size/M

#578 add hpa support
  api/v1alpha1/commonwebui_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  bundle/manifests/operators.ibm.com_commonwebuis.yaml
  config/crd/bases/operators.ibm.com_commonwebuis.yaml
  controllers/commonwebui/commonwebui_controller.go
  controllers/resources/deepequals.go
  controllers/resources/deployments.go
  controllers/resources/horizontalpodautoscalers.go
  helm-cluster-scoped/templates/00-operators.ibm.com_commonwebuis.yaml
  helm/templates/00-rbac.yaml
  main.go
Labels: size/L, approved
