Repository IBM/ibm-commonui-operator, pull requests merged in 2025-04, with the labels that each got.

#579 add predicate for HPA
  controllers/commonwebui/commonwebui_controller.go
  controllers/resources/constants.go
  controllers/resources/horizontalpodautoscalers.go
Labels: approved, size/M

#584 cicd version bump automation for pipelines/CS-sc2.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#583 updates for aqua scan
  go.mod
  go.sum
  triggerfile
Labels: approved, size/XS

#585 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-commonui-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#582 updates for aqua scan
  go.mod
  go.sum
Labels: approved, size/XS

#581 change cert rotation label to true
  controllers/resources/certificates.go
Labels: approved, size/XS
